const koleksiyon = [
  {
    title: "Piramit Yatak Odası",
    caption: "Ahşapın göz alıcı formu",
    src: "./img/koleksiyon/piramit-yatak.jpg",
    category: "Yatak Odası",
    name: "Piramit",
    galleryPath: "./urun/piramit-yatak/",
    galleryImageCount: 6,
    rIndex: 0,
  },
  {
    title: "Piramit Yemek Odası",
    caption: "Özgün parçalarıyla evinizin atmosferini değiştirecek",
    src: "./img/koleksiyon/piramit-yemek.jpg",
    category: "Yemek Odası",
    name: "Piramit",
    galleryPath: "./urun/piramit-yemek/",
    galleryImageCount: 9,
    rIndex: 1,
  },
  {
    title: "Alya Yatak Odası",
    caption: "Rahatlığı ve şıklığı bir araya getiriyor",
    src: "./img/koleksiyon/alya-yatak.jpg",
    category: "Yatak Odası",
    name: "Alya",
    galleryPath: "./urun/alya-yatak/",
    galleryImageCount: 11,
    rIndex: 2,
  },
  {
    title: "Alya Yemek Odası",
    caption: "Göz alıcı detaylarıyla evinizin havasını değiştirecek",
    src: "./img/koleksiyon/alya-yemek.jpg",
    category: "Yemek Odası",
    name: "Alya",
    galleryPath: "./urun/alya-yemek/",
    galleryImageCount: 11,
    rIndex: 3,
  },
  {
    title: "Ardıç Yatak Odası",
    caption: "Özgün detaylarıyla konfordan ödün vermeyenler için",
    src: "./img/koleksiyon/ardic-yatak.jpg",
    category: "Yatak Odası",
    name: "Ardıç",
    galleryPath: "./urun/ardic-yatak/",
    galleryImageCount: 12,
    rIndex: 4,
  },
  {
    title: "Ardıç Yemek Odası",
    caption: "Her bir detayı özenle tasarlandı",
    src: "./img/koleksiyon/ardic-yemek.jpg",
    category: "Yemek Odası",
    name: "Ardıç",
    galleryPath: "./urun/ardic-yemek/",
    galleryImageCount: 7,
    rIndex: 5,
  },
  {
    title: "Country Yatak Odası",
    caption: "Klasik mobilyalarla modern evler için",
    src: "./img/koleksiyon/country-yatak.jpg",
    category: "Yatak Odası",
    name: "Country",
    galleryPath: "./urun/country-yatak/",
    galleryImageCount: 11,
    rIndex: 6,
  },
  {
    title: "Petek Yatak Odası",
    caption: "Zerafet ve şıklığın buluştuğu",
    src: "./img/koleksiyon/petek-yatak.jpg",
    category: "Yatak Odası",
    name: "Petek",
    galleryPath: "./urun/petek-yatak/",
    galleryImageCount: 9,
    rIndex: 7,
  },
  {
    title: "Petek Yemek Odası",
    caption: "Modern dokunuşlarla evinizi bambaşka bir yere götürecek",
    src: "./img/koleksiyon/petek-yemek.jpg",
    category: "Yemek Odası",
    name: "Petek",
    galleryPath: "./urun/petek-yemek/",
    galleryImageCount: 11,
    rIndex: 8,
  },
  {
    title: "Pirinç Yatak Odası",
    caption: "Eşsiz tasarımıyla evinize eşlik edecek",
    src: "./img/koleksiyon/pirinc-yatak.jpg",
    category: "Yatak Odası",
    name: "Pirinç",
    galleryPath: "./urun/pirinc-yatak/",
    galleryImageCount: 12,
    rIndex: 9,
  },
  {
    title: "Pirinç Yemek Odası",
    caption: "Gösterişli tasarımıyla salonunuza yeni bir soluk getirecek",
    src: "./img/koleksiyon/pirinc-yemek.jpg",
    category: "Yemek Odası",
    name: "Pirinç",
    galleryPath: "./urun/pirinc-yemek/",
    galleryImageCount: 13,
    rIndex: 10,
  },
  {
    title: "Wood Yatak Odası",
    caption: "Zarif dizaynıyla sadelik arayanlar için",
    src: "./img/koleksiyon/wood-yatak.jpg",
    category: "Yatak Odası",
    name: "Wood",
    galleryPath: "./urun/wood-yatak/",
    galleryImageCount: 15,
    rIndex: 11,
  },
  {
    title: "Wood Yemek Odası",
    caption: "Modern planıyla rahatlık sunan",
    src: "./img/koleksiyon/wood-yemek.jpg",
    category: "Yemek Odası",
    name: "Wood",
    galleryPath: "./urun/wood-yemek/",
    galleryImageCount: 13,
    rIndex: 12,
  },
];

export { koleksiyon };
